((markdown-mode . ((eval . (drew/slides-mode 1))))
 (makefile-mode . ((eval . (drew/slides-mode 1))))
 (css-mode      . ((eval . (drew/slides-mode 1))))
 (org-mode      . ((eval . (drew/slides-mode 1))))
)
